### ISSUE TITLE
Check if translated pages are properly handled?

### ISSUE THREAD

**Issue by sypets** [b13/xray#9]
I checked if translated pages are handled. This does not look right:

```
| 31678 | tt_content | 123225 | bodytext | http://site-uol/en/students | t3://page?uid=15145   |
```

It should be:` t3://page?uid=15145&_language=1`

The URL http://site-uol/en/students resolves to a translated page (sys_language_uid=1).

```
base: 'https://example.org'
baseVariants:
  -
    base: '%env(URL)%'
    condition: 'applicationContext == "Development/%env(SHORTCUT)%"'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    flag: de
  -
    title: English
    enabled: true
    languageId: 1
    base: /en/
    typo3Language: default
    locale: en_US.UTF8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ltr
    fallbackType: strict
    fallbacks: '0'
    flag: gb

```
